<?php

namespace App\Repository;

use App\Entity\Callback;

/**
 * CallbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallbackRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteCallback(Callback $callback)
    {
        return $this
            ->createQueryBuilder('callback')
            ->delete()
            ->where('callback.id = :id')
            ->setParameter('id', $callback)
            ->getQuery()
            ->getResult()
        ;
    }
}