<?php

namespace App\Repository;

use App\Entity\Category;
use App\Entity\Product;
use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
	public function findAllProducts()
	{
		return $this
			->createQueryBuilder('product')
			->getQuery()
			->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY)
		;
	}

    public function findActiveProduct($id)
    {
        return $this
            ->createQueryBuilder('product')
            ->where('product.id = :id')
            ->andWhere('product.active = true')
            ->setParameter('id',  $id)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }

	public function findActiveByCategory(Category $category)
	{
		return $this
			->createQueryBuilder('product')
			->join('product.category', 'category')
			->where('category.active = true')
			->andWhere('product.active = true')
			->getQuery()
			->getResult()
		;
	}

	public function deleteProduct(Product $product)
    {
        return $this
            ->createQueryBuilder('product')
            ->delete()
            ->where('product.id = :id')
            ->setParameter('id', $product)
            ->getQuery()
            ->getResult()
        ;
    }

    public function getImageByProduct(Product $product)
    {
        return $this
            ->createQueryBuilder('product')
            ->select('product.image')
            ->where('product.id = :id')
            ->setParameter('id', $product)
            ->getQuery()
            ->getResult()
        ;
    }
}