<?php

namespace App\Repository;

use App\Entity\Tag;
use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function deleteTag(Tag $tag)
    {
        return $this
            ->createQueryBuilder('tag')
            ->delete()
            ->where('tag.id = :id')
            ->setParameter('id', $tag)
            ->getQuery()
            ->getResult()
        ;
    }
}