<?php

namespace App\Repository;

use App\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteUser(User $user)
    {
        return $this
            ->createQueryBuilder('user')
            ->delete()
            ->where('user.id = :id')
            ->setParameter('id', $user)
            ->getQuery()
            ->getResult()
        ;
    }
}
